name: Test igloo_driver modules

on:
  pull_request:
    branches: [main]

env:
  REGISTRY: ${{ secrets.REHOSTING_ARC_REGISTRY || 'harbor.harbor.svc.cluster.local' }}
  USER: ${{ secrets.REHOSTING_ARC_REGISTRY_USER || 'external' }}
  CACHE: ${{ secrets.REHOSTING_ARC_REGISTRY && format('{0}/proxy', secrets.REHOSTING_ARC_REGISTRY) || 'docker.io' }}
  TARGET: ${{ secrets.REHOSTING_ARC_REGISTRY || 'harbor.harbor.svc.cluster.local/external' }}
  EXTERNAL_REGISTRY_PASS: 'PctyVGasz15Pn9M0yA9yMNwOawFaXnk3Tl4N'

jobs:
  build:
    runs-on: rehosting-arc
    steps:
      - name: Checkout igloo_driver
        uses: actions/checkout@v4

      - name: Trust Harbor's self-signed certificate
        run: |
          echo "Fetching certificate from ${{ secrets.REHOSTING_ARC_REGISTRY }}"
          openssl s_client -showcerts -connect ${{ secrets.REHOSTING_ARC_REGISTRY }}:443 < /dev/null 2>/dev/null | openssl x509 -outform PEM | sudo tee /usr/local/share/ca-certificates/harbor.crt > /dev/null
          sudo update-ca-certificates

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:master
            network=host
          buildkitd-config-inline: |
            [registry."${{ secrets.REHOSTING_ARC_REGISTRY }}"]
              insecure = true
              http = true

      - name: Log in to Rehosting Arc Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USER }}
          password: ${{ secrets.REHOSTING_ARC_REGISTRY_PASSWORD || env.EXTERNAL_REGISTRY_PASS }}

      - name: Pull toolchain image via Buildx and Load to Daemon
        run: |
          echo "FROM ${{secrets.REHOSTING_ARC_REGISTRY}}/proxy/rehosting/embedded-toolchains:latest" | \
          docker buildx build -t embedded-toolchains:latest --load -

      - name: Download kernel-devel-all from release if not present
        run: |
          if [ ! -f local_packages/kernel-devel-all.tar.gz ]; then
            mkdir -p local_packages
            curl -L -o local_packages/kernel-devel-all.tar.gz "https://github.com/rehosting/linux_builder/releases/latest/download/kernel-devel-all.tar.gz"
          fi
      - name: Install pigz
        run: |
          sudo apt-get update
          sudo apt-get install -y pigz

      - name: Extract and build all modules
        run: |
          ./build.sh --versions "4.10 6.13" \
            --image embedded-toolchains:latest \
            --release
